
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install graphviz
install:
  - pip install -r requirements.txt
script:
  - cd src/lyra/unittests/
  - PYTHONPATH="${PYTHONPATH}:../../"
  - export PYTHONPATH
  - python test_SignLattice.py
  - python test_IntervalLattice.py
  - python test_UsageLattice.py
  - python sign_tests.py
  - python interval_tests.py
  - python liveness_tests.py
  - python usage_tests.py
  - python assumption_tests.py
